"""Stress test: time-loss accuracy when simulated laps violate the estimator's assumptions.

Validating on laps generated by the estimator's own model (pre-clip power = d x cap, sharp
clipping, level road) overstates accuracy. Each scenario here breaks one assumption, then
all at once, using a separate simulator so no code is shared with the estimator's model.
"""
import argparse

import numpy as np
import pandas as pd

from erslens.laptime import clip_time_loss
from erslens.params import load_car_params
from erslens.physics import G, mguk_cap_kmh

DS = 2.0
LENGTH_M = 1300.0
SCENARIOS = {
    "in-model": dict(constant_power=False, ramp=False, grade=0.0),
    "constant pre-clip power": dict(constant_power=True, ramp=False, grade=0.0),
    "gradual clipping (50 kW/s)": dict(constant_power=False, ramp=True, grade=0.0),
    "2% uphill": dict(constant_power=False, ramp=False, grade=0.02),
    "all three": dict(constant_power=True, ramp=True, grade=0.02),
}


def drive(car, ice, cda, mass, v0, pre, clip_m, harvest_w, ramp, grade, constant_power):
    n = int(LENGTH_M / DS)
    s = np.arange(n) * DS
    v = np.empty(n)
    v[0], p = v0, None
    for k in range(n - 1):
        cap = float(mguk_cap_kmh(v[k] * 3.6, car))
        pre_power = min(pre, cap) if constant_power else pre * cap
        target = pre_power if s[k] < clip_m else -harvest_w
        if p is None or not ramp:
            p = target
        else:
            step = car.mguk_ramp_w_per_s * DS / v[k]
            p = float(np.clip(target, p - step, p + step))
        f = min((ice + p) / v[k], car.traction_max_n)
        a = (f - 0.5 * car.rho * cda * v[k] ** 2 - car.crr * mass * G - mass * G * grade) / mass
        v[k + 1] = np.sqrt(max(v[k] ** 2 + 2 * a * DS, 25.0))
    return s, v


def telemetry(s, v, rng):
    t = np.concatenate([[0.0], np.cumsum(2 * DS / (v[1:] + v[:-1]))])
    tt = np.arange(0, t[-1], 0.25)
    kmh = np.round(np.interp(tt, t, v) * 3.6 + rng.normal(0, 0.8, len(tt)))
    return pd.DataFrame({"time_s": tt, "distance_m": np.interp(tt, t, s), "speed_kmh": kmh,
                         "throttle": 100.0, "brake": False})


def span_time(s, v, a, b):
    m = (s >= a) & (s <= b)
    vv = v[m]
    return float(np.sum(2 * DS / (vv[1:] + vv[:-1])))


def run_scenario(cfg, n, rng, car):
    rows = []
    while len(rows) < n:
        ice = car.ice_power_w * rng.uniform(0.9, 1.1)
        cda = car.cda_straight * rng.uniform(0.8, 1.2)
        mass = car.mass_kg + rng.uniform(0, car.fuel_kg)
        pre = rng.uniform(150e3, 350e3) if cfg["constant_power"] else rng.uniform(0.4, 1.0)
        clip_m, harvest = rng.uniform(0.35, 0.7) * LENGTH_M, rng.uniform(5e4, 3e5)
        v0 = rng.uniform(58.0, 66.0)
        args = (car, ice, cda, mass, v0, pre)
        s, v = drive(*args, clip_m, harvest, cfg["ramp"], cfg["grade"], cfg["constant_power"])
        _, v_free = drive(*args, 1e9, 0.0, cfg["ramp"], cfg["grade"], cfg["constant_power"])
        if int(np.argmax(v)) > len(v) - 10:
            continue
        elevation = (s, cfg["grade"] * s) if cfg["grade"] else None
        est = clip_time_loss(telemetry(s, v, rng), 0, 1e6, car.mass_kg + car.fuel_kg / 2, car, elevation)
        if est is None or not est["clipping"]:
            continue
        a, b = est["span_from_m"], est["span_to_m"]
        truth = span_time(s, v, a, b) - span_time(s, v_free, a, b)
        rows.append((truth, est["t_loss_s"], est["interval_low_s"], est["interval_high_s"]))
    return pd.DataFrame(rows, columns=["true_s", "est_s", "low_s", "high_s"])


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--n", type=int, default=30)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--scenarios", nargs="*", default=list(SCENARIOS))
    args = p.parse_args()
    car = load_car_params("configs/car_2026.yaml")
    print(f"{'scenario':28s} {'median |err|':>12s} {'bias':>8s} {'90% |err|':>10s} {'rel. median':>12s} {'interval covers':>16s}")
    for name in args.scenarios:
        df = run_scenario(SCENARIOS[name], args.n, np.random.default_rng(args.seed), car)
        err = df.est_s - df.true_s
        covered = ((df.true_s >= df.low_s) & (df.true_s <= df.high_s)).mean()
        print(f"{name:28s} {err.abs().median():11.3f}s {err.median():+7.3f}s {err.abs().quantile(0.9):9.3f}s "
              f"{(err / df.true_s).abs().median():11.1%} {covered:15.0%}", flush=True)


if __name__ == "__main__":
    main()
